version: 3
jobs:
  build:
    docker:
      image: abhinavkishoregv/ruby-custom
      auth:
        username: $DOCKER_USERNAME
        password: $DOCKER_PASSWORD
    steps:
      - checkout
      - sonarcloud/scan
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.0

workflows:
  version: 3
  main:
    jobs:
      - build:
          context: SonarCloud
